import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

import WhiteList from '../components/Whitelist';

export default function Home() {
  const [collections, setCollections] = useState([]);


  const start = () => {
    console.log("HelloOOOOO")
  }
  
  useEffect( () => {
    start();
  }, [collections]);

  return (
    <div className={styles.container}>
      <Head>
        <title>WhiteList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black flex justify-center w-screen h-fit text-white  '>
        <WhiteList
          collections={collections}
          setCollections={setCollections}
        />
      </main>
      
    </div>
  )
}
