import Head from 'next/head'
import { stringify } from 'postcss';
import styles from '../styles/Home.module.css'


export default function Home() {
  const address = "KT1EpGgjQs73QfFJs9z7m1Mxm5MTnpC2tqse"
  const hackedAccount = "tz1RH8gwbXe4PBTNrJzCDLuhDnDJw8ck5tm6"
  const collectionId = "4752" // this is the collection ID for TezOrigins Cracks in the Cryptoverse - Rarity A
  const collectionId2 = "4753"  // this is the collection ID for TezOrigins A Marriage of Ideals - Rarity A
  const tokenId = "53256"
  const symbol = "TZORG"
  const name = "collections"
  const collectionName = "Chapter 00: Tezception"
  const creatorName = "tezosorigins"
  //const api = `https://api.tzkt.io/v1/tokens?metadata.collectionId=${collectionId}`;
  const api = `https://api.tzkt.io/v1/tokens/balances?token.metadata.collectionId=${collectionId}&account.ne=${hackedAccount}`;

  //const api2 = `https://api.tzkt.io/v1/tokens?metadata.collectionName=${collectionName}`
  const apiOptions = { mode: "no-cors" }

  const whitelist = async (url, options) => {

    const res = await fetch(url);
    console.log(res);
    const data = await res.json()
    console.log(data);
}
const test = async (url, options) => {

  const res = await fetch(url);
  console.log(res);
  const data = await res.json()
  console.log(data);
}



const accounts = whitelist(api, apiOptions);
//const testing = test(api2, apiOptions)

  return (
    <div className={styles.container}>
      <Head>
        <title>WhiteList</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-black flex justify-center text-white w-screen h-screen '>
        <div className=" bg-slate-600 flex justify-center p-10 m-10 rounded-xl">
          <section >
            {}
          </section>
        </div>
      </main>
      
    </div>
  )
}
